# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'serial_tool.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(781, 539)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setAutoFillBackground(False)
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_3.setSpacing(1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.cob_UpDown = QtWidgets.QComboBox(Form)
        self.cob_UpDown.setObjectName("cob_UpDown")
        self.cob_UpDown.addItem("")
        self.cob_UpDown.addItem("")
        self.gridLayout.addWidget(self.cob_UpDown, 1, 7, 1, 1)
        self.pb_MakeStation = QtWidgets.QPushButton(Form)
        self.pb_MakeStation.setObjectName("pb_MakeStation")
        self.gridLayout.addWidget(self.pb_MakeStation, 1, 9, 1, 1)
        self.pb_OpenOrClose = QtWidgets.QPushButton(Form)
        self.pb_OpenOrClose.setObjectName("pb_OpenOrClose")
        self.gridLayout.addWidget(self.pb_OpenOrClose, 1, 2, 1, 1)
        self.cob_Com = QtWidgets.QComboBox(Form)
        self.cob_Com.setObjectName("cob_Com")
        self.gridLayout.addWidget(self.cob_Com, 1, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 5, 1, 1)
        self.chk_HexSend = QtWidgets.QCheckBox(Form)
        self.chk_HexSend.setObjectName("chk_HexSend")
        self.gridLayout.addWidget(self.chk_HexSend, 2, 9, 1, 1)
        self.pb_Send = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_Send.sizePolicy().hasHeightForWidth())
        self.pb_Send.setSizePolicy(sizePolicy)
        self.pb_Send.setObjectName("pb_Send")
        self.gridLayout.addWidget(self.pb_Send, 4, 9, 1, 1)
        self.sp_CircleT = QtWidgets.QSpinBox(Form)
        self.sp_CircleT.setObjectName("sp_CircleT")
        self.gridLayout.addWidget(self.sp_CircleT, 1, 6, 1, 1)
        self.chk_HexRecv = QtWidgets.QCheckBox(Form)
        self.chk_HexRecv.setObjectName("chk_HexRecv")
        self.gridLayout.addWidget(self.chk_HexRecv, 1, 3, 1, 1)
        self.sp_Station = QtWidgets.QSpinBox(Form)
        self.sp_Station.setObjectName("sp_Station")
        self.gridLayout.addWidget(self.sp_Station, 1, 8, 1, 1)
        self.pb_ClearRecv = QtWidgets.QPushButton(Form)
        self.pb_ClearRecv.setObjectName("pb_ClearRecv")
        self.gridLayout.addWidget(self.pb_ClearRecv, 1, 4, 1, 1)
        self.lbl_Com = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_Com.sizePolicy().hasHeightForWidth())
        self.lbl_Com.setSizePolicy(sizePolicy)
        self.lbl_Com.setObjectName("lbl_Com")
        self.gridLayout.addWidget(self.lbl_Com, 1, 0, 1, 1)
        self.te_Recv = QtWidgets.QTextEdit(Form)
        self.te_Recv.setObjectName("te_Recv")
        self.gridLayout.addWidget(self.te_Recv, 0, 0, 1, 10)
        self.te_Send = QtWidgets.QTextEdit(Form)
        self.te_Send.setObjectName("te_Send")
        self.gridLayout.addWidget(self.te_Send, 2, 0, 3, 9)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.lbl_Status = QtWidgets.QLabel(Form)
        self.lbl_Status.setObjectName("lbl_Status")
        self.gridLayout_3.addWidget(self.lbl_Status, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Serial Tool"))
        self.cob_UpDown.setItemText(0, _translate("Form", "Up"))
        self.cob_UpDown.setItemText(1, _translate("Form", "Down"))
        self.pb_MakeStation.setText(_translate("Form", "MakeStation"))
        self.pb_OpenOrClose.setText(_translate("Form", "打开(&O)"))
        self.chk_HexSend.setText(_translate("Form", "Hex Send"))
        self.pb_Send.setText(_translate("Form", "Send(&S)"))
        self.chk_HexRecv.setText(_translate("Form", "Hex Recv"))
        self.pb_ClearRecv.setText(_translate("Form", "Clear Recv"))
        self.lbl_Com.setText(_translate("Form", "TextLabel"))
        self.lbl_Status.setText(_translate("Form", "TextLabel"))

